
name: Test

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  CLONE_LINK: https://github.com/hraj9258/telegram_bot
  CHAT_ID: ${{ secrets.CHAT_ID }}
  BOT_TOKKEN: ${{ secrets.BOT_TOKKEN }}
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
             
       - name: Sync source and device tree
         run: |
             mkdir work
             cd work
             git clone $CLONE_LINK
             
       - name: Uploading test zip to telegram
         run: |
              cd work/telegram_bot
              sudo zip -r9 test.zip META-INF
              curl -F chat_id=$CHAT_ID -F document=@test.zip -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKKEN/sendDocument
